### ISSUE TITLE
in need of some quoting love?

### ISSUE THREAD

**Issue by testdept** [textpattern/textpattern-plugin-template#1]
got an error (Txp 4.6.1, PHP 5.5.38) while using "zem_plugin_example.php" in folder "/full/path/dev/plugins" and ied_plugin_composer plugin (1.1.0), culprit seems line 48 of "zem_plugin_example.php"

needs some quoting love, suggestion...

`$plugin['flags'] = "'". PLUGIN_HAS_PREFS | PLUGIN_LIFECYCLE_NOTIFY ."'";`

**Comment by philwareham** [comment]
Hi @Bloke 
This is your area of expertise, any suggestions?

**Comment by Bloke** [comment]
Sure. Leave it with me. I have some updates to the template already done actually, just haven't got round to committing them yet.

**Comment by testdept** [comment]
looking forward to your suggestion + updates, appreciated!
thx for the goodies, haha

**Comment by testdept** [comment]
my bad, not an error with "zem_plugin_example.php"
[fixed by Bloke](https://github.com/Bloke/ied_plugin_composer/commit/d473e1481bfb2d48a2fab1d1d05e19ea522761e2)
