### ISSUE TITLE
Update textile parser for help files to new method

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern-plugin-template#5]
The plugin template still refers to the now defunct `classTextile.php`. jsoo has a [PR](https://github.com/textpattern/textpattern-plugin-template/pull/3#issue-110373909) but I believe that is also for an earlier iteration of the new class-based method.

**Comment by Bloke** [comment]
Thank you! That patch looks pretty reasonable so I might steal the best bits and just commit them. It's not mergable as-is because I'm so lazy I didn't even see it had a PR raised and things have moved on. Leave it with me.
